export const defaultElements = {
    text: {
        label: "Text",
        value: "text",
        component: "text",
        data: {
            title: "Text",
            x: 150,
            y: 15,
            text: "Simple Text yellow",
            fontSize: 30,
            fontFamily: "Calibri",
            fill: "green",
            color: "red",
            component: "text",
            id: 111,
        },
    },
    rectangle: {
        label: "Rectangle",
        component: "rectangle",
        value: "rectangle",
        data: {
            x: 10,
            y: 10,
            width: 100,
            height: 100,
            fill: "red",
            color: "yellow",
        },
    },
    circle: {
        label: "Circle",
        component: "circle",
        value: "circle",
        data: {
            x: 100,
            y: 100,
            radius: 70,
            fill: "red",
            stroke: "black",
            strokeWidth: 4,
        },
    },
    star: {
        label: "Star",
        value: "Star",
        component: "star",
        data: {
            x: 100,
            y: 100,
            numPoints: 5,
            innerRadius: 40,
            outerRadius: 70,
            fill: "red",
            stroke: "black",
            strokeWidth: 4,
        },
    },
};
