export const defaultElements = {
    text: {
        label: "Text",
        value: "text",
        component: "text",
        type: "text",
        data: {
            text: "Simple Text",
            x: 80,
            y: 80,
            strokeDasharray: 0,
            fontSize: 30,
            fontFamily: "Calibri",
            fill: "green",
            stroke: "red",
            strokeWidth: 1,
        },
    },
    rectangle: {
        label: "Rectangle",
        component: "rectangle",
        value: "rectangle",
        type: "rectangle",
        data: {
            x: 80,
            y: 80,
            width: 100,
            height: 100,
            fill: "green",
            color: "yellow",
        },
    },
    circle: {
        label: "Circle",
        component: "circle",
        value: "circle",
        type: "circle",
        data: {
            x: 80,
            y: 80,
            radius: 70,
            fill: "red",
            stroke: "black",
            strokeWidth: 4,
        },
    },
    star: {
        label: "Star",
        value: "Star",
        component: "star",
        type: "star",
        data: {
            x: 110,
            y: 110,
            numPoints: 5,
            innerRadius: 40,
            outerRadius: 70,
            fill: "red",
            stroke: "black",
            strokeWidth: 4,
        },
    },
};
